### ISSUE TITLE
Contract validate error

### ISSUE THREAD

**Issue by liukai1055** [tronprotocol/trident#85] opened 2023-06-08 09:20 UTC
I encountered a contract error while trading USDT using TRX， this is the error: OTHER_ERROR, <ByteString@1d0dfe55 size=85 contents="Contract validate error : account [TWwborJAnhn1...",  could give me some help.

**Comment by Cletitia** [comment] 2023-06-12 08:01
The causes of `OTHER_ERROR`s can be retrieved only from the node logs.

**Comment by xq-lu** [comment] 2023-06-15 09:25
> 

hi, @liukai1055 
When you happened to encounter a contract error, please refer to this doc https://developers.tron.network/docs/faq#12-broadcast-response-code , which lists the most occurred error code/cause/solution.
As in your case, this error happened in the transaction validation process. It seems like a problem with your transaction itself. 
Could you post the complete error message or provide how you construct your transaction?

**Comment by vivian-kang** [comment] 2023-07-13 07:00
Thanks for your contribution to trident, this issue will be closed as no update for a long time.

Please feel free to re-open it if it still exists, thanks.

**Closed by vivian-kang** 2023-07-13 07:00 UTC
